### ISSUE TITLE
Hexe 

### ISSUE THREAD

**Issue by Vortal4** [NgGH707/NgGH-Magic-Origins-Mod#10]
there is an invisible hexe dialog. I cannot click or do anything else.

[log.zip](https://github.com/NgGH707/NgGH-Magic-Origins-Mod/files/11140259/log.zip)

**Comment by NgGH707** [comment]
I don't know why is this happened. From the log, it states the event starts by you have no hexe background in your roster. It baffles me because the elder hexe background is what causes the event to occur

**Comment by Vortal4** [comment]
I may have added the Hexe AFTER starting a new game with Breditor. As it was working last years, I didn't think at the time that that could be the problem.
