### ISSUE TITLE
Start and hexe bugs

### ISSUE THREAD

**Issue by EnryuTower** [NgGH707/NgGH-Magic-Origins-Mod#5]
This is the first mod I am playing along with legends and I cannot get the hexe start to work. In the OP version it just sits on the creating settlements screen forever when I try to start a campaign, and on the balance version it won't let me leave settlements when entered, accept contracts, or kill enemies in combat (they go to zero health and leave a corpse then become untargetable and keep fighting). 

The geomancer and mage trio sit on world gen screen in both versions.
Thank you

**Comment by Smerf4321** [comment]
Hi, just to add to this. I tried the Cabal start as well and results are the same as Mage Trio and Geomancers

I've tried 3.1.9 and 3.1.8 versions with the current 16.0.6 Legends version.

It doesn't seem to be affecting any other starts, but I cannot say if there are any issues in-game as I've just tried starting a campaign.

**Comment by Vortal4** [comment]
It doesn't seem to be compatible with mod_legends_16_0_9 with either version.
