### ISSUE TITLE
Endless loading bug when fighting against goblins

### ISSUE THREAD

**Issue by Sharrim97** [NgGH707/NgGH-Magic-Origins-Mod#8]
Endless loading bug showed after 90 days ingame, earlier everything was fine.
[log.zip](https://github.com/NgGH707/NgGH-Magic-Origins-Mod/files/11068710/log.zip)

**Comment by NgGH707** [comment]
Thanks! I can see what is the problem now

**Comment by Sharrim97** [comment]
Newest update fixed this bug. Nice and quick job, thanks.
